### PR TITLE
Added secret option to fluentbit depployment in helm chart

### PR DESCRIPTION
**Pull request by deveshk0**
- This PR Add secrets option in helm chart, by which you can define custom secrets which should be mounted to your fluentbit deployment. This help in adding Client certs or CA cert to the fluentBit deployment.

- Fixed some typo error

### CODE REVIEW

**Comment by wenchajun** [comment]
Thank you for your contribution. Because of a recent commit https://github.com/fluent/fluentbit-operator/pull/189 , `fluentbit-operator` has changed to `fluentd-operator`. Since this is a huge change, this pr is better placed in the [fluentbit-operator branch](https://github.com/fluent/fluentbit-operator/tree/fluentbit-operator).  helm will also be updated soon.

**Comment by deveshk0** [comment]
I guess my base has all the latest commit, should I rebase to [fluentbit-operator](https://github.com/fluent/fluentbit-operator/tree/fluentbit-operator) ?

**Comment by wenchajun** [comment]
Yes, thank you for your contribution. Maybe we can submit this contribution in both `master` and `fluentbit-operator.`

**Comment by deveshk0** [comment]
I will switch branches to `fluentbit-operator` and later we can merge `fluentbit-operator` to master

**Review by benjaminhuo — APPROVED** [review]

**Pull request merged**
