### PR TITLE
Optionally enabled namespace scoped RBAC

### PR DESCRIPTION
**Pull request by bojand**
#133 expands permissions to cluster-scoped level, undoing RBAC changes introduced in #117.
This introduces scoped permissions again, now dynamically used only if specific namespace(s) are watched.
The manifests are added to enable dynamic configuration. By default it should stay cluster scoped.

EDIT: not sure what's up with git history 🤔

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@wanjunlei @wenchajun Please help to review this.

What are the potential problems after changing from namespaced RBAC?
What plugins do not work properly as described in #133?

**Comment by wenchajun** [comment]
If the role is bound to the namespace, the Filter plug-in will not work well. It does not have permissions to access the default namespace under kubeURL: https://kubernetes.default.svc:443
https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/filter-kubernetes.yaml#L13

**Review by wenchajun — COMMENTED** [review]
Is this still clusterRole？

**Comment by benjaminhuo** [comment]
> https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/filter-kubernetes.yaml#L13

It means if using namespaced RBAC, the `default` namespace has to be added to the allowed namespace list?

**Comment by wenchajun** [comment]
> > https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/filter-kubernetes.yaml#L13
> 
> It means if using namespaced RBAC, the `default` namespace has to be added to the allowed namespace list?

yes,  the filter token and CAfile have only roles permissions. https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/filter-kubernetes.yaml#L13-L16

**Comment by bojand** [comment]
The change proposed keeps the cluster role configuration as the default, so I think it should work the same untouched. Hence there are no changes to `+kubebuilder:rbac` code generation directives in the Go source code. 

The scoped RBAC only comes into play if `--watch-namespaces` option is used. I think the assumption and intent there is that the fluentbit operator users probably have some specific scoping / security intent and some customization of RBAC and configurations is probably needed on the client's end. Which might be reasonable expectation? We do not know ahead of time the namespace(s) targeted and how to configure the necessary bindings. So the new added patch yamls introduced here for the role are more for a "starting point" I suppose, and not necessarily something that would work out of the box for every scenario. But maybe there is room for improvement.

**Comment by benjaminhuo** [comment]
> The change proposed keeps the cluster role configuration as the default, so I think it should work the same untouched. Hence there are no changes to `+kubebuilder:rbac` code generation directives in the Go source code.
> 
> The scoped RBAC only comes into play if `--watch-namespaces` option is used. I think the assumption and intent there is that the fluentbit operator users probably have some specific scoping / security intent and some customization of RBAC and configurations is probably needed on the client's end. Which might be reasonable expectation? We do not know ahead of time the namespace(s) targeted and how to configure the necessary bindings. So the new added patch yamls introduced here for the role are more for a "starting point" I suppose, and not necessarily something that would work out of the box for every scenario. But maybe there is room for improvement.

@bojand @nicktate The changes you made are good to me, especially when the switch is added. 
I understood the scenario you mentioned.
If user want to add the `--watch-namespaces`, it's better to add the `default` namespace to the list because FluentBit cannot get the metadata of k8s if it's not added https://github.com/fluent/fluentbit-operator/blob/master/manifests/logging-stack/filter-kubernetes.yaml#L13-L16

**Pull request merged**
