### PR TITLE
 use k8s master URL instead of `kubernetes.default.svc `

### PR DESCRIPTION
**Pull request by wenchajun**
Users can customize the service. However, in the case of multiple nodes, the hosts files on each machine are different, so you need to adjust the hosts files.

Please see for more details https://github.com/fluent/fluentbit-operator/issues/184

Signed-off-by: chengdehao <dehaocheng@kubesphere.io>

### CODE REVIEW

**Comment by wenchajun** [comment]
The user can generate the corresponding FluentBitPod through this configuration
b1878a0b37bd4559dc0ddc599fd9a94
65a7d6c0c9c1fdb95d0503a8edad27b

**Review by wanjunlei — APPROVED** [review]

**Comment by wanjunlei** [comment]
Please update the doc, use k8s master URL instead of `kubernetes.default.svc`.

**Comment by benjaminhuo** [comment]
Just like the code below:
K8s API is defined as `Spec.Template.Spec.Volumes` and `Spec.Template.Spec.Containers[0].VolumeMounts`
The field we defined in FB crd should follow the same schema: `Volumes` and `VolumeMounts`

```go
	if fb.Spec.Volumes !=nil {
		ds.Spec.Template.Spec.Volumes=append(ds.Spec.Template.Spec.Volumes,fb.Spec.Volumes...)
	}
	if fb.Spec.VolumesMount !=nil {
		ds.Spec.Template.Spec.Containers[0].VolumeMounts=append(ds.Spec.Template.Spec.Containers[0].VolumeMounts,fb.Spec.VolumesMount...)
	}
```

**Comment by wenchajun** [comment]
> Just like the code below: K8s API is defined as `Spec.Template.Spec.Volumes` and `Spec.Template.Spec.Containers[0].VolumeMounts` The field we defined in FB crd should follow the same schema: `fb.Spec.Volumes` and `fb.Spec.VolumeMounts` @wenchajun
> 
> ```go
> 	if fb.Spec.Volumes !=nil {
> 		ds.Spec.Template.Spec.Volumes=append(ds.Spec.Template.Spec.Volumes,fb.Spec.Volumes...)
> 	}
> 	if fb.Spec.VolumesMount !=nil {
> 		ds.Spec.Template.Spec.Containers[0].VolumeMounts=append(ds.Spec.Template.Spec.Containers[0].VolumeMounts,fb.Spec.VolumesMount...)
> 	}
> ```
But this may increase the burden of users. We may need to create multiple structures. 
Our CR currently looks like this:
```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
  fluentBitConfigName: fluent-bit-config
  image: 'kubesphere/fluent-bit:v1.8.3'
  positionDB:
    emptyDir: {}
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 25Mi
  tolerations:
    - operator: Exists
  volumes:
    - hostPath:
        path: /etc/hosts
        type: File
      name: hosts
  volumesMount:
    - mountPath: /etc/hosts
      name: hosts
      readOnly: true
```

**Comment by benjaminhuo** [comment]
I mean you define `VolumesMount` as an array, it should be `VolumesMounts` just like k8s API does

```go
	// List of volumes that can be mounted by containers belonging to the pod.
	Volumes []corev1.Volume `json:"volumes,omitempty"`
	// Pod volumes to mount into the container's filesystem.
	VolumesMount  []corev1.VolumeMount  `json:"volumesMount,omitempty"`
```

**Review by benjaminhuo — APPROVED** [review]

**Comment by florian-asche** [comment]
> > Just like the code below: K8s API is defined as `Spec.Template.Spec.Volumes` and `Spec.Template.Spec.Containers[0].VolumeMounts` The field we defined in FB crd should follow the same schema: `fb.Spec.Volumes` and `fb.Spec.VolumeMounts` @wenchajun
> > ```go
> > 	if fb.Spec.Volumes !=nil {
> > 		ds.Spec.Template.Spec.Volumes=append(ds.Spec.Template.Spec.Volumes,fb.Spec.Volumes...)
> > 	}
> > 	if fb.Spec.VolumesMount !=nil {
> > 		ds.Spec.Template.Spec.Containers[0].VolumeMounts=append(ds.Spec.Template.Spec.Containers[0].VolumeMounts,fb.Spec.VolumesMount...)
> > 	}
> > ```
> 
> But this may increase the burden of users. We may need to create multiple structures. Our CR currently looks like this:
> 
> ```
> spec:
>   affinity:
>     nodeAffinity:
>       requiredDuringSchedulingIgnoredDuringExecution:
>         nodeSelectorTerms:
>           - matchExpressions:
>               - key: node-role.kubernetes.io/edge
>                 operator: DoesNotExist
>   fluentBitConfigName: fluent-bit-config
>   image: 'kubesphere/fluent-bit:v1.8.3'
>   positionDB:
>     emptyDir: {}
>   resources:
>     limits:
>       cpu: 500m
>       memory: 200Mi
>     requests:
>       cpu: 10m
>       memory: 25Mi
>   tolerations:
>     - operator: Exists
>   volumes:
>     - hostPath:
>         path: /etc/hosts
>         type: File
>       name: hosts
>   volumesMount:
>     - mountPath: /etc/hosts
>       name: hosts
>       readOnly: true
> ```

yeah. I want fluent-bit to write the logfiles with the file output module. How can i mount a volume inside my fluent-bit container?

**Pull request merged**
